WebApplication1/Models/ResistorCalcuator.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;


namespace HoustonElectronics.ResistorCalculator.Web.Models
{


    public class ResistorCalculatorModel
    {
        public ResistorCalculatorModel()
        {
            CalculatedResult = "No result currently calculated.";
            HasFourBands = true;
        }

        [Display(Name = "Color for First Band")]
        [Required]
        public String ColorBandFirst
        {
            get;
            set;
        }

        [Display(Name = "Color for Second Band")]
        [Required]
        public String ColorBandSecond
        {
            get;
            set;
        }

        [Display(Name = "Color for Third Band")]
        [Required]
        public String ColorBandThird
        {
            get;
            set;
        }

        [Display(Name = "Color for Fourth Band")]
        [Required]
        public String ColorBandFourth
        {
            get;
            set;
        }

        [Display(Name = "Color for Fifth Band")]
        [Required]
        public String ColorBandFifth
        {
            get;
            set;
        }



        [Display(Name = "Calculated Result")]
        public String CalculatedResult
        {
            get;
            set;
        }


        [Display(Name = "Calculated Result")]
        public String MoreAccurateResult
        {
            get;
            set;
        }

        
        [Display(Name = "Only has four bands")]
        public bool HasFourBands
        {
            get;
            set;
        }


        public SelectList SignificantOnly
        {
            get
            {
                String[] significantDigitList = { "Black", "Blue", "Brown", "Gray", "Green", "Orange", "Red", "Violet", "Yellow", "White" };
                return new SelectList(significantDigitList);
            }
        }

        public SelectList MultiplierOnly
        {
            get
            {
                String[] significantDigitList = { "Black", "Blue", "Brown", "Gold", "Gray", "Green", "Red", "Silver", "Violet", "Yellow" };
                return new SelectList(significantDigitList);
            }
        }

        public SelectList ToleranceOnly
        {
            get
            {
                String[] significantDigitList = { "Blue", "Brown", "Gold", "Gray", "Green", "None", "Red", "Silver", "Violet", "Yellow"};
                return new SelectList(significantDigitList);
            }
        }

        public SelectList MultiplierOrTolerance
        {
            get
            {
                String[] significantDigitList = { "Black", "Blue", "Brown", "Gold", "Gray", "Green", "None", "Red", "Silver", "Violet", "Yellow" };
                return new SelectList(significantDigitList);
            }
        }

        public SelectList AllPossible
        {
            get
            {
                String[] significantDigitList = { "Black", "Blue", "Brown", "Gold", "Gray", "Green", "None", "Orange", "Red", "Silver", "Violet", "White", "Yellow" };
                return new SelectList(significantDigitList);
            }
        }
    }

}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using HoustonElectronics.ResistorCalculator.Web.Models;
using HoustonElectronics.ResistorCalculator.Calculator;

namespace HoustonElectronics.ResistorCalculator.Web.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.ShowResistor = false;
            return View(new ResistorCalculatorModel());
        }

        [HttpPost]
        public ActionResult Index(ResistorCalculatorModel model)
        {
            try
            {
                OhmValueCalculator calc = new OhmValueCalculator();
                int ohmResult = calc.CalculateOhmValue(model.ColorBandFirst, model.ColorBandSecond, model.ColorBandThird, model.ColorBandFourth);

                model.CalculatedResult = String.Format("The resistor specified is {0:n0} Ohms", ohmResult);

                ViewBag.ShowResistor = true;
                ViewBag.ColorBandFirst = model.ColorBandFirst.ToUpper();
                ViewBag.ColorBandSecond = model.ColorBandSecond.ToUpper();
                ViewBag.ColorBandThird = model.ColorBandThird.ToUpper();
                ViewBag.ColorBandFourth = model.ColorBandFourth.ToUpper();


            }
            catch (Exception ex)
            {
                ViewBag.ShowResistor = false;
                model.CalculatedResult = String.Format("Error occurred: {0}", ex.Message);
            }

            return View(model);
        }
    }


}

WebApplication1/Controllers/V2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using HoustonElectronics.ResistorCalculator.Web.Models;
using HoustonElectronics.ResistorCalculator.Calculator;

namespace HoustonElectronics.ResistorCalculator.Web.Controllers
{
    public class V2Controller : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.ShowResistor = false;
            return View(new ResistorCalculatorModel());
        }

        public ActionResult V2()
        {
            ViewBag.ShowResistor = false;
            return View(new ResistorCalculatorModel());
        }

        [HttpPost]
        public ActionResult Index(ResistorCalculatorModel model)
        {
            try
            {
                OhmValueCalculator calc = new OhmValueCalculator();

                calc.AddBand(model.ColorBandFirst, BandIndex.FIRST);
                calc.AddBand(model.ColorBandSecond, BandIndex.SECOND);
                calc.AddBand(model.ColorBandThird, BandIndex.THIRD);
                calc.AddBand(model.ColorBandFourth, BandIndex.FOURTH);

                if (!model.HasFourBands)
                {
                    calc.AddBand(model.ColorBandFifth, BandIndex.FIFTH);
                }


                calc.Calculate();

                model.CalculatedResult = String.Format("The resistor specified is {0:n} Ohms and {1}% Tolerance", calc.GetOhmValue(), calc.GetTolerance());


                ViewBag.HasFourBands = model.HasFourBands;
                ViewBag.ShowResistor = true;
                ViewBag.ColorBandFirst = model.ColorBandFirst.ToUpper();
                ViewBag.ColorBandSecond = model.ColorBandSecond.ToUpper();
                ViewBag.ColorBandThird = model.ColorBandThird.ToUpper();
                ViewBag.ColorBandFourth = model.ColorBandFourth.ToUpper();
                ViewBag.ColorBandFifth = model.ColorBandFifth.ToUpper();
            }
            catch (Exception ex)
            {
                ViewBag.ShowResistor = false;
                model.CalculatedResult = String.Format("Error occurred: {0}", ex.Message);
            }

            return View(model);
        }
    }


}

WebApplication1/Views/Home/Index.cshtml
@model ResistorCalculatorModel
@{
    ViewBag.Title = "Simple Resistor Calculator";
}
<h3>V1 (POC)</h3>
<br/><br/>
<p>
    Welcome to my submission for <a href="http://www.blinds.com" target="REUSABLE_POPUP">Blinds.com</a>.
    <br/><br />
    Initially, I like to do a proof of concept to ensure we have an excellent starting point.  From this moment going forward, we can assume all of the base functionality works correctly within this project.  Please follow the directions and enjoy!
</p>
@using (Html.BeginForm("Index", "Home", FormMethod.Post, new
{
    role = "form"
}))
{
    <table cellpadding="10" style="width: 500px;">
        <tr>
            <td colspan="2">
                <table cellpadding="8" class="STEP_TABLE">
                    <tr>
                        <td><div class="STEP_NUMBER">1</div></td>
                        <td class="DIRECTIONS">Please select the color code of the resistor by reading the resistor from left to right.  To distinguish left from right, there is a tiny gap between the third and fourth bands.</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.ColorBandFirst)
            </td>
            <td>
                @Html.DropDownListFor(model => model.ColorBandFirst, Model.SignificantOnly, new { @class = "POC_DROP_LIST" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.ColorBandSecond)
            </td>
            <td>
                @Html.DropDownListFor(model => model.ColorBandSecond, Model.SignificantOnly, new { @class = "POC_DROP_LIST" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.ColorBandThird)
            </td>
            <td>
                @Html.DropDownListFor(model => model.ColorBandThird, Model.MultiplierOnly, new { @class = "POC_DROP_LIST" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.ColorBandFourth)
            </td>
            <td>
                @Html.DropDownListFor(model => model.ColorBandFourth, Model.ToleranceOnly, new { @class = "POC_DROP_LIST" })
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <table cellpadding="8" class="STEP_TABLE">
                    <tr>
                        <td><div class="STEP_NUMBER">2</div></td>
                        <td class="DIRECTIONS">Click the button below to calculate the result.</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td colspan="2" align="center">
                <input type="submit" value="Submit" />
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <table cellpadding="8" class="STEP_TABLE">
                    <tr>
                        <td><div class="STEP_NUMBER">3</div></td>
                        <td class="DIRECTIONS">View your result below.</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.CalculatedResult)
            <td>
                @Html.DisplayFor(model => model.CalculatedResult)
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <table cellpadding="8" class="STEP_TABLE">
                    <tr>
                        <td><div class="STEP_NUMBER">4</div></td>
                        <td class="DIRECTIONS">Compare visually with the resistor below to make certain.</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td colspan="3">
            @if (ViewBag.ShowResistor)
            {
                <svg width="500" height="50">
                    <rect y="20" width="150" height="7" style="fill:#C0C0C0;stroke-width:0;" />
                    <rect x="350" y="20" width="150" height="7" style="fill:#C0C0C0;stroke-width:0;" />
                    <rect x="150" width="200" rx="20" ry="20" height="45" style="fill:#fdc; stroke-width: 1; stroke:#000" />
                    <rect x="170" y="0" width="20" height="45" style="fill:@ViewBag.ColorBandFirst" />
                    <rect x="210" y="0" width="20" height="45" style="fill:@ViewBag.ColorBandSecond" />
                    <rect x="250" y="0" width="20" height="45" style="fill:@ViewBag.ColorBandThird" />
                    <rect x="310" y="0" width="20" height="45" style="fill:@ViewBag.ColorBandFourth" />
                </svg>
            }
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <table cellpadding="8" class="STEP_TABLE">
                    <tr>
                        <td><div class="STEP_NUMBER">5</div></td>
                        <td class="DIRECTIONS">Try Version 2 for more accurate results.</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                @Html.ActionLink("Click here for Version 2", "Index", "V2")
            </td>
        </tr>
    </table>

    <br/><br/>
    <p>
        This submission was created entirely by Charles Rollins.  I hope you find my work satisfactory.  I finished this work on 2016 / 08 / 09 05:22
        <br/><br/>
        Now to put it on github!
    </p>

    @Html.AntiForgeryToken()
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
        @RenderBody()
        
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/V2/Index.cshtml
@model ResistorCalculatorModel
@{
    ViewBag.Title = "Simple Resistor Calculator";
}
<h3>V2 (More accurate values)</h3>
<br/><br/>
<p>
    Welcome back!</a>.
    <br/><br />
    Now we work on getting more accurate results and extensibility.  This one has support for 5 possible bands.
</p>
@using (Html.BeginForm("Index", "V2", FormMethod.Post, new
{
    role = "form"
}))
{
    <table cellpadding="10" style="width: 500px;">
        <tr>
            <td colspan="2">
                <table cellpadding="8" class="STEP_TABLE">
                    <tr>
                        <td><div class="STEP_NUMBER">1</div></td>
                        <td class="DIRECTIONS">Please select the color code of the resistor by reading the resistor from left to right.  To distinguish left from right, there is a tiny gap between the third and fourth bands.</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.ColorBandFirst)
            </td>
            <td>
                @Html.DropDownListFor(model => model.ColorBandFirst, Model.SignificantOnly, new { @class = "POC_DROP_LIST" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.ColorBandSecond)
            </td>
            <td>
                @Html.DropDownListFor(model => model.ColorBandSecond, Model.SignificantOnly, new { @class = "POC_DROP_LIST" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.ColorBandThird)
            </td>
            <td>
                @Html.DropDownListFor(model => model.ColorBandThird, Model.AllPossible, new { @class = "POC_DROP_LIST" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.ColorBandFourth)
            </td>
            <td>
                @Html.DropDownListFor(model => model.ColorBandFourth, Model.MultiplierOrTolerance, new { @class = "POC_DROP_LIST" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.ColorBandFifth)
            </td>
            <td>
                @Html.DropDownListFor(model => model.ColorBandFifth, Model.ToleranceOnly, new { @class = "POC_DROP_LIST" })
                <br/>
                @Html.LabelFor(model => model.HasFourBands)
                @Html.CheckBoxFor(model => model.HasFourBands)
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <table cellpadding="8" class="STEP_TABLE">
                    <tr>
                        <td><div class="STEP_NUMBER">2</div></td>
                        <td class="DIRECTIONS">Click the button below to calculate the result.</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td colspan="2" align="center">
                <input type="submit" value="Submit" />
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <table cellpadding="8" class="STEP_TABLE">
                    <tr>
                        <td><div class="STEP_NUMBER">3</div></td>
                        <td class="DIRECTIONS">View your result below.</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.CalculatedResult)
            <td>
                @Html.DisplayFor(model => model.CalculatedResult)
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <table cellpadding="8" class="STEP_TABLE">
                    <tr>
                        <td><div class="STEP_NUMBER">4</div></td>
                        <td class="DIRECTIONS">Compare visually with the resistor below to make certain.</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td colspan="3">
            @if (ViewBag.ShowResistor)
            {

                if (ViewBag.HasFourBands)
                {
                    <svg width="500" height="50">
                        <rect y="20" width="150" height="7" style="fill:#C0C0C0;stroke-width:0;" />
                        <rect x="350" y="20" width="150" height="7" style="fill:#C0C0C0;stroke-width:0;" />
                        <rect x="150" width="200" rx="20" ry="20" height="45" style="fill:#fdc; stroke-width: 1; stroke:#000" />
                        <rect x="170" y="0" width="20" height="45" style="fill:@ViewBag.ColorBandFirst" />
                        <rect x="210" y="0" width="20" height="45" style="fill:@ViewBag.ColorBandSecond" />
                        <rect x="250" y="0" width="20" height="45" style="fill:@ViewBag.ColorBandThird" />
                        <rect x="310" y="0" width="20" height="45" style="fill:@ViewBag.ColorBandFourth" />
                    </svg>
                }
                else
                {
                    <svg width="500" height="50">
                        <rect y="20" width="150" height="7" style="fill:#C0C0C0;stroke-width:0;" />
                        <rect x="350" y="20" width="150" height="7" style="fill:#C0C0C0;stroke-width:0;" />
                        <rect x="150" width="200" rx="20" ry="20" height="45" style="fill:#fdc; stroke-width: 1; stroke:#000" />
                        <rect x="170" y="0" width="16" height="45" style="fill:@ViewBag.ColorBandFirst" />
                        <rect x="200" y="0" width="16" height="45" style="fill:@ViewBag.ColorBandSecond" />
                        <rect x="230" y="0" width="16" height="45" style="fill:@ViewBag.ColorBandThird" />
                        <rect x="260" y="0" width="16" height="45" style="fill:@ViewBag.ColorBandFourth" />
                        <rect x="300" y="0" width="16" height="45" style="fill:@ViewBag.ColorBandFifth" />
                    </svg>
                }
            }
            </td>
        </tr>
    </table>
    @Html.AntiForgeryToken()
}
<p>
    This small project was completed entirely by Charles Rollins on 2016/09/08 at 6:50 AM
</p>